create_clock -name clk -period 20.0 [get_ports clk]
set_input_delay 4.0 -clock clk [delete_from_list [all_inputs] [get_ports clk]]
set_output_delay 4.0 -clock clk [all_outputs]
set_load 0.02 [all_outputs]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_4 -pin X [delete_from_list [all_inputs] [get_ports clk]]
